<?php

namespace App\Services;

use App\Modules\CleanSlate\Models\Generation;
use Illuminate\Http\Client\RequestException;
use Illuminate\Support\Facades\Http;

class GitHubService
{
    private const API_BASE = 'https://api.github.com';

    public function __construct(private readonly string $token = '') {}

    /**
     * Create a new GitHub repository and push all generated files from a zip.
     *
     * @throws RequestException
     */
    public function pushGeneration(Generation $generation, string $repoName, string $userToken): string
    {
        $http = Http::withToken($userToken)
            ->withHeaders(['Accept' => 'application/vnd.github+json', 'X-GitHub-Api-Version' => '2022-11-28'])
            ->baseUrl(self::API_BASE);

        // 1. Get authenticated user to know the owner
        $viewer = $http->get('/user')->throw()->json();
        $owner = $viewer['login'];

        // 2. Create repo (fails gracefully if it already exists)
        $http->post('/user/repos', [
            'name' => $repoName,
            'description' => 'Generated by smbgen EXTREME — '.$generation->prompt,
            'private' => true,
            'auto_init' => false,
        ]);

        // 3. Extract zip and push each file as a blob + tree + commit
        $zipPath = storage_path('app/'.$generation->zip_path);

        if (! file_exists($zipPath)) {
            throw new \RuntimeException('Generation zip not found.');
        }

        $files = $this->extractZipContents($zipPath);

        $blobs = [];
        foreach ($files as $path => $content) {
            $blob = $http->post("/repos/{$owner}/{$repoName}/git/blobs", [
                'content' => base64_encode($content),
                'encoding' => 'base64',
            ])->throw()->json();

            $blobs[] = [
                'path' => $path,
                'mode' => '100644',
                'type' => 'blob',
                'sha' => $blob['sha'],
            ];
        }

        // 4. Get or create base tree
        $refsResponse = $http->get("/repos/{$owner}/{$repoName}/git/refs/heads/main");
        $baseTree = null;

        if ($refsResponse->successful()) {
            $baseTree = $refsResponse->json('object.sha');
        }

        $tree = $http->post("/repos/{$owner}/{$repoName}/git/trees", array_filter([
            'base_tree' => $baseTree,
            'tree' => $blobs,
        ]))->throw()->json();

        // 5. Create commit
        $commit = $http->post("/repos/{$owner}/{$repoName}/git/commits", array_filter([
            'message' => 'Initial commit via smbgen EXTREME',
            'tree' => $tree['sha'],
            'parents' => $baseTree ? [$baseTree] : [],
        ]))->throw()->json();

        // 6. Update or create main branch ref
        if ($refsResponse->successful()) {
            $http->patch("/repos/{$owner}/{$repoName}/git/refs/heads/main", [
                'sha' => $commit['sha'],
                'force' => true,
            ])->throw();
        } else {
            $http->post("/repos/{$owner}/{$repoName}/git/refs", [
                'ref' => 'refs/heads/main',
                'sha' => $commit['sha'],
            ])->throw();
        }

        return "https://github.com/{$owner}/{$repoName}";
    }

    /**
     * @return array<string, string>
     */
    private function extractZipContents(string $zipPath): array
    {
        $zip = new \ZipArchive;
        $files = [];

        if ($zip->open($zipPath) !== true) {
            throw new \RuntimeException('Could not open generation zip.');
        }

        for ($i = 0; $i < $zip->numFiles; $i++) {
            $name = $zip->getNameIndex($i);

            // Skip directories
            if (str_ends_with($name, '/')) {
                continue;
            }

            $files[$name] = $zip->getFromIndex($i);
        }

        $zip->close();

        return $files;
    }
}
